version: '3.8'

services:

  db:
    image: mysql:8.4
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agile_db
    ports:
      - "3307:3306"
    # expose:
    #   - '3306'
    # deja les service sont dans le meme reseau pas besoin de exposer des port interconteneur
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - myNet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 5
  back-end:
    build: .
    container_name: spring-backend-agile-app
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8090:8080"  # Host:Container
    networks:
      - myNet
    depends_on:
      db:
        condition: service_healthy
    # expose:
    #   - '8080' meme remarque


networks:
  myNet:
volumes:
  mysql-data:
